#
###################################
# Site wide configuration
####################################
#
title: Wen.onweb
email:
description: Sofware and Development
url: # the base hostname & protocol for your site
keywords: ["blog", "Linux kernel", "GPU drivers", "AMD", "display driver", "Linux", "Graphics"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          Europe/Lisbon
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /blog/:year/:month/:day/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: WEN.ONWEB
  avatar: melissa-wen.jpg
  job: "Melissa Wen"
  bio: "Software Developer @ Igalia"
  email:
  rss: true
  disqus-shortname:
  twitter: #username
  facebook: #username
  google:
    plus: #username
    analytics: UA-170178218-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: melissawen
  gitlab: mwen
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: melissa-wen-1b4bb539
  skype: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
  reddit: #username
  telegram: #username
